# Generated by Django 4.2 on 2023-04-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='account_no',
        ),
    ]
