# Generated by Django 4.2 on 2023-04-30 12:31

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0002_auto_20190504_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='diposit',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interest',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('percent', models.DecimalField(decimal_places=2, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('15'))])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approval', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
